name: 'RelizaHub submit metadata'
description: 'Submit Release metadata for a release on RelizaHub'
branding:
  icon: 'info'
  color: 'green'
inputs:
  reliza_api_id:
    description: "Reliza Hub API ID"
    required: true
  reliza_api_key:
    description: "Reliza Hub API KEY"
    required: true
  image_full_name:
    description: "Full name of the Docker image with registry prefix"
    required: true
  image_digest:
    description: "SHA 256 digest of the image artifact"
    required: true
  reliza_build_start:
    description: "Build start time"
    required: true
  reliza_full_version:
    description: "Version obtained from RelizaHub for this release"
    required: true
  reliza_build_status:
    description: "Build status - [complete | rejected]"
    required: true
  reliza_api_url:
    description: "Reliza Hub API URL"
    required: false
    default: 'https://app.relizahub.com'
  artifact_type:
    description: "Type of artifact created by this release [Docker, File]"
    required: false
    default: 'Docker'
  commit_list:
    description: "List of commits"
    required: false
runs:
  using: "composite"
  steps:
    - name: Instantiate Reliza status
      shell: bash
      run: echo "--status ${{inputs.reliza_build_status}} " > reliza_command
    - name: Submit metadata to Reliza Hub
      shell: bash
      run: |
        echo -n "-b ${{github.ref_name}} -k ${{ inputs.reliza_api_key }} \
          -i ${{ inputs.reliza_api_id }} -u ${{ inputs.reliza_api_url }} \
          -v ${{ inputs.reliza_full_version }} " >> reliza_command
        echo -n "--artid ${{inputs.image_full_name}} " >> reliza_command
        echo -n "--artbuildid github${{github.action}}${{github.sha}} " >> reliza_command
        echo -n "--artbuilduri https://github.com/${{github.repository}}/actions/runs/${{github.run_id}} " >> reliza_command
        echo -n "--artcimeta GitHub Actions " >> reliza_command
        echo -n "--arttype ${{inputs.artifact_type}} " >> reliza_command
        if [[ ${{inputs.image_digest}} != "" ]]
        then
          echo -n "--artdigests ${{inputs.image_digest}} " >> reliza_command
        fi
        if [ ! -z ${{inputs.commit_list}} ]
        then
          echo -n "--commits ${{inputs.commit_list}} " >> reliza_command
        fi
        echo -n "--datestart ${{inputs.reliza_build_start}} " >> reliza_command
        echo -n "--dateend $(date -Iseconds) " >> reliza_command
        # debug
        cat reliza_command
        # send data
        echo reliza-cli addrelease $(cat reliza_command) > rlz_cmd_exec
        eval $(cat rlz_cmd_exec)
    - name: Fail build if reliza status is rejected
      shell: bash
      run: |
        status_complete_check=$(cat reliza_command | grep 'status complete' | wc -l)
        if [[ "$status_complete_check" != "1" ]]
        then
          echo "Failing build since Reliza build Status is rejected"
          exit 1
        fi